# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f88c7cc292cbbb665a05162456042d82f28a39c79421af0e0212b4b6918760d83d4b85b76824d280f59932d361f3ca294f249f80da2bbd4f13b2d3f305d41d6c

test:
  secret_key_base: 10212802682ae2f5e64e436a5593fd2721c09173778c956ee31df68d05195d07a5fb24d7bbee0d44f3a8a9cf43a7250dbadda4a849c1dc6f4bbef311f15655f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
